export const types = Object.freeze({
  SET_FETCH_BASKET_PRODUCTS_REQUEST: 'SET_FETCH_BASKET_PRODUCTS_REQUEST',
  SET_FETCH_BASKET_PRODUCTS_SUCCESS: 'SET_FETCH_BASKET_PRODUCTS_SUCCESS',
  SET_FETCH_BASKET_PRODUCTS_ERROR: 'SET_FETCH_BASKET_PRODUCTS_ERROR',
});
