export const types = Object.freeze({
  SET_FETCH_STATISTICS_REQUEST: 'SET_FETCH_STATISTICS_REQUEST',
  SET_FETCH_STATISTICS_SUCCESS: 'SET_FETCH_STATISTICS_SUCCESS',
  SET_FETCH_STATISTICS_ERROR: 'SET_FETCH_STATISTICS_ERROR',
});
